// One-off build step: compiles contracts/NftRoundTripProbe.sol into
// src/risk/nftRoundTripProbeArtifact.js (bytecode + ABI as a plain JS module).
// Not run at boot — solc is a devDependency, not shipped/required at
// runtime. Re-run manually with `node scripts/compileNftRoundTripProbe.js` any
// time NftRoundTripProbe.sol changes.
import fs from "node:fs";
import path from "node:path";
import solc from "solc";

const contractPath = path.join(process.cwd(), "contracts", "NftRoundTripProbe.sol");
const source = fs.readFileSync(contractPath, "utf8");

const input = {
  language: "Solidity",
  sources: { "NftRoundTripProbe.sol": { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.deployedBytecode.object"] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

const errors = (output.errors || []).filter((e) => e.severity === "error");
if (errors.length > 0) {
  for (const e of errors) console.error(e.formattedMessage);
  process.exit(1);
}

const contract = output.contracts["NftRoundTripProbe.sol"]["NftRoundTripProbe"];
const artifact = {
  abi: contract.abi,
  // Runtime/deployed bytecode, NOT creation bytecode — this gets planted
  // directly at an address via eth_call's state override, so it must be the
  // code the EVM executes on a call, not a constructor that (when executed
  // as-is, ignoring calldata) just returns the runtime code as its result.
  bytecode: "0x" + contract.evm.deployedBytecode.object,
};

const outPath = path.join(process.cwd(), "src", "risk", "nftRoundTripProbeArtifact.js");
fs.writeFileSync(
  outPath,
  `// Generated by scripts/compileNftRoundTripProbe.js from contracts/NftRoundTripProbe.sol — do not hand-edit.\n` +
    `export const nftRoundTripProbeAbi = ${JSON.stringify(artifact.abi, null, 2)};\n\n` +
    `export const nftRoundTripProbeBytecode = ${JSON.stringify(artifact.bytecode)};\n`
);

console.log(`Wrote ${outPath}`);
